# Generated by Django 5.0.2 on 2024-03-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('data', models.DateField()),
                ('vendor', models.TextField()),
                ('icon', models.TextField()),
                ('image', models.ImageField(upload_to='spendingapp/imagini/')),
            ],
        ),
    ]
