# Generated by Django 5.0.2 on 2024-03-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
